development:
  adapter: mysql2
  encoding: utf8
  database: resourcemap_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: resourcemap_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: resourcemap
  pool: 5
  username: root
  password: 
