development:
  secret_key: RECAPTCHA_SECRET_KEY
  site_key: RECAPTCHA_SITE__KEY

test:
  secret_key: RECAPTCHA_SECRET_KEY
  site_key: RECAPTCHA_SITE__KEY

production:
  secret_key: RECAPTCHA_SECRET_KEY
  site_key: RECAPTCHA_SITE__KEY
