mobile_id: on
host: 54.169.173.164:8080
number_of_attempt_failed: 5

plugins:
  public_collection: on
  snapshot: on
  channels: on
  reminders: off
  alerts: on
  account_completeness: on
  fred_api: on
